<LoginScreen>:
    GridLayout:
        GridLayout:
            Label: "User Login"
        TextInput:
            hint_text: "Username"
        TextInput:
            hint_text: "Password"
        Button:
            text: "Login"

        GridLayout:
            cols:2
            Button:
                text: "Forgot Password"
            Button:
                text: "Sign up"

<RootWidget>:
    LoginSceen:
        name: "login_screen"